addons:
    apt:
        update: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.stack

before_install:
    - sudo apt-get install -y build-essential m4 openjdk-8-jdk libgmp-dev libmpfr-dev pkg-config flex bison z3 libz3-dev maven opam python3 cmake gcc clang-8 lld-8 llvm-8-tools zlib1g-dev libboost-test-dev libyaml-dev libjemalloc-dev
    - curl -sSL https://get.haskellstack.org/ | sh
    - git clone --recursive https://github.com/kframework/k "$HOME/k-framework"
    - (cd "$HOME/k-framework" && mvn -B clean -DskipTests -pl "!llvm-backend" package)

script:
    - time make kompile
    - time make exec
    - time make typecheck

