addons:
    apt:
        update: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.stack

before_install:
    - curl -sSL https://get.haskellstack.org/ | sh

script:
    - (cd Compiler && stack test)

