#!/usr/bin/env bash

set -e

KDISTR="$HOME/k-framework/k-distribution/bin"
FLAGS=()

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

directory="dynamic/"

if [[ "$1" == "typecheck" ]]; then
    shift
    directory="static/"

    if [[ "$1" == "debug" ]]; then
        shift
        FLAGS+=("--log")
        FLAGS+=("--log-cells")
        FLAGS+=("(k),(#pc),#result,(typeEnv)")
    fi
elif [[ "$1" == "compile" ]]; then
    shift
    directory="compiler/"
    if [[ "$1" == "debug" ]]; then
        shift
        FLAGS+=("--log")
        FLAGS+=("--log-cells")
        FLAGS+=("(k),(#pc),#result")
    fi
else
    if [[ "$1" == "debug" ]]; then
        shift
        FLAGS+=("--log")
        FLAGS+=("--log-cells")
        FLAGS+=("(k),(#pc),#result,(storage),(lookup),(localTypeEnv)")
    fi
fi

if [[ "$1" == "test" ]]; then
    shift

    fname=""

    for arg in "$@"; do
        if [[ ! "$arg" =~ "^--" ]]; then
            fname="$arg"
            break
        fi
    done

    if [[ -z "$fname" ]]; then
        echo "No filename specified!"
        exit 1
    fi

    result="fail"
    if [[ -e "$fname.out" ]]; then
        if "$KDISTR/krun" "${FLAGS[@]}" --directory "$directory" "$@" | diff - "$fname.out"; then
            result="pass"
        fi
    else
        echo "[ERROR] No output file for $fname!"
        exit 1
    fi

    if [[ "$result" == "fail" ]]; then
        echo -e "${RED}[ERROR] $fname failed${NC}"
        exit 1
    else
        echo -e "${GREEN}[INFO] $fname passed${NC}"
    fi
else
    set -x
    "$KDISTR/krun" --directory "$directory" "${FLAGS[@]}" "$@"
fi

